// packages/backend/src/core/marketplace.ts
// DaShengOS Skill Marketplace — 从 WorkBuddy 已安装技能导入的完整目录

export interface SkillManifest {
  version: string
  author: string
  category: string
  tags: string[]
  capabilities: string[]
  required_config: Record<string, { type: string; label: string; default?: string }>
  rlimits?: { cpu?: string; memory?: string; timeout_sec?: number }
}

export interface MarketplaceEntry {
  id: string
  name: string
  description: string
  category: string
  version: string
  author: string
  installs: number
  rating: number
  manifest: SkillManifest
  body?: string
}

export const MARKETPLACE_CATALOG: MarketplaceEntry[] = [
  // ---- automation (自动化) ----
  {
    id: 'wb-playwright-mcp',
    name: 'Playwright MCP',
    description: '通过 Playwright MCP 协议自动化浏览器：导航、截图、表单填写、数据提取。',
    category: 'automation',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'automation',
      tags: ["automation", "playwright_mcp", "mcp"],
      capabilities: ["playwright-mcp"],
      required_config: {},
    },
  },
  {
    id: 'wb-playwright',
    name: 'Playwright 自动化+抓取',
    description: 'Playwright 浏览器自动化：同时支持 MCP 协议和直接 API 调用，覆盖自动化、抓取和测试。',
    category: 'automation',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'automation',
      tags: ["automation", "playwright"],
      capabilities: ["playwright"],
      required_config: {},
    },
  },
  {
    id: 'wb-scrapling-official',
    name: 'Scrapling 网页抓取',
    description: '使用 Scrapling 高效抓取网页：反反爬虫、智能元素定位、结构化数据提取。',
    category: 'automation',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'automation',
      tags: ["automation", "scrapling_official"],
      capabilities: ["scrapling-official"],
      required_config: {},
    },
  },
  {
    id: 'wb-peekaboo',
    name: 'macOS UI 自动化',
    description: '通过 Peekaboo CLI 捕获和自动化 macOS UI：截图、点击、输入、读取界面元素。',
    category: 'automation',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'automation',
      tags: ["automation", "peekaboo"],
      capabilities: ["peekaboo"],
      required_config: {},
    },
  },
  {
    id: 'wb-claude-agent-team-workflows',
    name: '多 Agent 团队编排',
    description: '通用多 Agent 工作流编排器，支持角色定义、任务分配、协作链和结果聚合。',
    category: 'automation',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'automation',
      tags: ["automation", "claude_agent_team_wo"],
      capabilities: ["claude-agent-team-workflows"],
      required_config: {},
    },
  },
  {
    id: 'wb-automation-workflows',
    name: '自动化工作流',
    description: '设计并执行自动化工作流编排，支持多步骤串联、条件分支和定时触发。',
    category: 'automation',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'automation',
      tags: ["automation", "automation_workflows"],
      capabilities: ["automation-workflows"],
      required_config: {},
    },
  },

  // ---- content (内容创作) ----
  {
    id: 'wb-humanizer',
    name: 'AI 去痕迹器',
    description: '消除 AI 生成文本的痕迹：去除过度符号化、模板化表达，让文本更自然、更像人写。',
    category: 'content',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'content',
      tags: ["content", "humanizer"],
      capabilities: ["humanizer"],
      required_config: {},
    },
  },
  {
    id: 'wb-book-writer',
    name: 'AI 著书引擎',
    description: 'AI 辅助著书：根据提示词生成大纲并逐级扩写，支持章节拆分和内容修订。',
    category: 'content',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'content',
      tags: ["content", "book_writer"],
      capabilities: ["book-writer"],
      required_config: {},
    },
  },
  {
    id: 'wb-fbs-bookwriter',
    name: 'FBS 人机协同著书',
    description: '中文人机协同著书与长文档生成器：书籍、企业手册、行业白皮书与指南，支持大纲到逐章扩写。',
    category: 'content',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'content',
      tags: ["content", "fbs_bookwriter"],
      capabilities: ["fbs-bookwriter"],
      required_config: {},
    },
  },
  {
    id: 'wb-blogwatcher',
    name: '博客 RSS 监控',
    description: '监控博客和 RSS/Atom 订阅源，自动检测新文章、提取摘要、发送通知。',
    category: 'content',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'content',
      tags: ["content", "blogwatcher"],
      capabilities: ["blogwatcher"],
      required_config: {},
    },
  },

  // ---- custom (通用工具) ----
  {
    id: 'wb-agency-agents',
    name: 'AI Agent 61 专家团',
    description: '61 个专业 Agent、8 大部门的完整企业级 AI 组织架构，覆盖运营/营销/开发/设计等全域。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "agency_agents"],
      capabilities: ["agency-agents"],
      required_config: {},
    },
  },
  {
    id: 'wb-ai-agent-helper',
    name: 'AI Agent 优化助手',
    description: 'AI Agent Prompt Engineering 与配置优化助手，帮助调优 Agent 的提示词和行为参数。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "ai_agent_helper"],
      capabilities: ["ai-agent-helper"],
      required_config: {},
    },
  },
  {
    id: 'wb-agent-mail',
    name: 'AI 邮箱',
    description: 'AI Agent 专属邮箱：收发邮件、管理消息、通过 @agentmail.to 地址与其他 Agent 通信。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "agent_mail"],
      capabilities: ["agent-mail"],
      required_config: {},
    },
  },
  {
    id: 'wb-sag',
    name: 'ElevenLabs TTS',
    description: 'ElevenLabs 文字转语音：mac 风格 say 体验，支持多语言、声音克隆和 SSML 控制。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "sag"],
      capabilities: ["sag"],
      required_config: {},
    },
  },
  {
    id: 'wb-hermes-troubleshoot',
    name: 'Hermes 故障排查',
    description: 'Hermes Agent Gateway 故障诊断：连接断开、超时、协议错误等问题的排查和修复。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "hermes_troubleshoot"],
      capabilities: ["hermes_agent_故障排查技能"],
      required_config: {},
    },
  },
  {
    id: 'wb-whatsapp-business',
    name: 'WhatsApp Business',
    description: 'WhatsApp Business API 集成：商业消息、模板管理、客户服务和自动化回复。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "whatsapp_business"],
      capabilities: ["whatsapp-business"],
      required_config: {},
    },
  },
  {
    id: 'wb-zustand-persist-tdz-fix',
    name: 'Zustand TDZ 修复',
    description: '修复前端 Zustand persist 导致的 TDZ 错误：页面卡 loading、Cannot access before init。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "zustand_persist_tdz_"],
      capabilities: ["zustand-persist-tdz-fix"],
      required_config: {},
    },
  },
  {
    id: 'wb-cellcog',
    name: '全能子代理 CellCog',
    description: 'Any-to-any AI 子代理：一句话请求即可完成研究、图片、视频、音频、文档、代码等多种输出。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "cellcog"],
      capabilities: ["cellcog"],
      required_config: {},
    },
  },
  {
    id: 'wb-multi-search-engine',
    name: '多搜索引擎',
    description: '多搜索引擎聚合：同时搜索 Google、Bing、DuckDuckGo 等引擎，汇总排序结果。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "multi_search_engine"],
      capabilities: ["multi-search-engine"],
      required_config: {},
    },
  },
  {
    id: 'wb-agent-browser-core',
    name: '浏览器自动化核心',
    description: '基于 OpenClaw 的浏览器自动化核心引擎，支持页面交互、截图、数据抓取等操作。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "agent browser core"],
      capabilities: ["agent_browser_core"],
      required_config: {},
    },
  },
  {
    id: 'wb-workbuddy-channel-setup',
    name: '渠道配置',
    description: 'WorkBuddy 渠道设置和配置管理：自定义连接器、认证设置和工作流绑定。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "workbuddy_channel_se"],
      capabilities: ["workbuddy-channel-setup"],
      required_config: {},
    },
  },
  {
    id: 'wb-lexiang-knowledge-base',
    name: '腾讯乐享知识库',
    description: '访问腾讯乐享知识库平台：搜索文档、管理知识空间、组织培训资料。',
    category: 'custom',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'custom',
      tags: ["custom", "lexiang_knowledge_ba"],
      capabilities: ["lexiang-knowledge-base"],
      required_config: {},
    },
  },

  // ---- data (数据分析) ----
  {
    id: 'wb-openai-whisper-api',
    name: 'Whisper API 语音转写',
    description: '通过 OpenAI Audio Transcription API 将音频转为文字，支持多语言和时间戳。',
    category: 'data',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'data',
      tags: ["data", "openai_whisper_api", "api"],
      capabilities: ["openai-whisper-api"],
      required_config: {},
    },
  },
  {
    id: 'wb-summarize',
    name: '内容摘要',
    description: '用 summarize CLI 汇总网页、PDF、图片、音频、YouTube 等多种来源的内容。',
    category: 'data',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'data',
      tags: ["data", "summarize"],
      capabilities: ["summarize"],
      required_config: {},
    },
  },
  {
    id: 'wb-weather',
    name: '天气查询',
    description: '获取当前天气和预报数据：无需 API Key，支持全球城市和多日预报。',
    category: 'data',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'data',
      tags: ["data", "weather"],
      capabilities: ["weather"],
      required_config: {},
    },
  },
  {
    id: 'wb-openai-whisper',
    name: '本地 Whisper 语音转写',
    description: '本地 Whisper 模型语音转文字：无需 API Key，支持多语言、长音频和实时转写。',
    category: 'data',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'data',
      tags: ["data", "openai_whisper"],
      capabilities: ["openai-whisper"],
      required_config: {},
    },
  },
  {
    id: 'wb-qmd',
    name: '本地搜索引擎',
    description: 'BM25 + 向量 + 重排序的本地搜索索引 CLI，支持 MCP 模式和语义检索。',
    category: 'data',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'data',
      tags: ["data", "qmd"],
      capabilities: ["qmd"],
      required_config: {},
    },
  },
  {
    id: 'wb-video-transcript-downloader',
    name: '视频字幕下载',
    description: '下载视频、音频、字幕和注释：支持 YouTube、B站等多平台，自动转写和翻译。',
    category: 'data',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'data',
      tags: ["data", "video_transcript_dow", "视频"],
      capabilities: ["video-transcript-downloader"],
      required_config: {},
    },
  },
  {
    id: 'wb-video-frames',
    name: '视频帧提取',
    description: '从视频提取帧或短片段：指定时间点截图、批量帧序列、创建 GIF 预览。',
    category: 'data',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'data',
      tags: ["data", "video_frames", "视频"],
      capabilities: ["video-frames"],
      required_config: {},
    },
  },
  {
    id: 'wb-songsee',
    name: '音频可视化',
    description: '从音频生成频谱图和特征面板可视化，支持波形、频谱和 MFCC 分析。',
    category: 'data',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'data',
      tags: ["data", "songsee"],
      capabilities: ["songsee"],
      required_config: {},
    },
  },

  // ---- design (视觉设计) ----
  {
    id: 'wb-agnes-ai-image',
    name: 'Agnes 图片生成',
    description: '基于 OpenAI 协议的 AI 图片生成与编辑 API，支持文生图、图生图、批量生成。',
    category: 'design',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'design',
      tags: ["design", "agnes_ai_image", "图片"],
      capabilities: ["agnes-ai-image"],
      required_config: {},
    },
  },
  {
    id: 'wb-agnes-ai-video',
    name: 'Agnes 视频生成',
    description: '基于异步轮询的 AI 视频生成 API，支持文生视频、图生视频等多种创作模式。',
    category: 'design',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'design',
      tags: ["design", "agnes_ai_video", "视频"],
      capabilities: ["agnes-ai-video"],
      required_config: {},
    },
  },
  {
    id: 'wb-ima-all-ai',
    name: 'IMA Studio',
    description: '最全面的 AI 内容创作工作室：图片、视频、音频、文档一站式生成与编辑。',
    category: 'design',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'design',
      tags: ["design", "ima_all_ai"],
      capabilities: ["ima-all-ai"],
      required_config: {},
    },
  },
  {
    id: 'wb-ima-skills',
    name: 'IMA 知识管理',
    description: 'IMA OpenAPI 统一技能：笔记管理和知识库操作，支持创建、检索和组织知识资产。',
    category: 'design',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'design',
      tags: ["design", "ima_skills"],
      capabilities: ["ima-skills"],
      required_config: {},
    },
  },
  {
    id: 'wb-nano-banana-pro',
    name: 'Nano Banana 图片',
    description: '使用 Nano Banana Pro API 生成和编辑 AI 图片，支持文生图、图生图、风格迁移。',
    category: 'design',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'design',
      tags: ["design", "nano_banana_pro"],
      capabilities: ["nano-banana-pro"],
      required_config: {},
    },
  },
  {
    id: 'wb-openai-image-gen',
    name: 'OpenAI 图片批量生成',
    description: '通过 OpenAI Image API 批量生成图片：支持多种尺寸、风格预设和批量队列。',
    category: 'design',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'design',
      tags: ["design", "openai_image_gen", "图片"],
      capabilities: ["openai-image-gen"],
      required_config: {},
    },
  },
  {
    id: 'wb-qwen-image',
    name: 'Qwen 图片生成',
    description: '使用 Qwen Image API 生成 AI 图片：文生图、风格迁移、多语言 prompt 支持。',
    category: 'design',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'design',
      tags: ["design", "qwen_image", "图片"],
      capabilities: ["qwen-image"],
      required_config: {},
    },
  },
  {
    id: 'wb-ui-ux-pro-max',
    name: 'UI/UX Pro Max',
    description: 'UI/UX 设计智能和实现引擎：从设计规范到代码生成，覆盖交互设计和前端实现。',
    category: 'design',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'design',
      tags: ["design", "ui_ux_pro_max"],
      capabilities: ["ui-ux-pro-max"],
      required_config: {},
    },
  },

  // ---- development (开发工具) ----
  {
    id: 'wb-cli-anything',
    name: 'CLI 生成器',
    description: '为任何工具或服务生成 Agent 可用的 CLI 命令行接口，标准化参数和输出格式。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "cli_anything"],
      capabilities: ["cli-anything"],
      required_config: {},
    },
  },
  {
    id: 'wb-oneapi-sys-flow',
    name: 'OneAPI 前端修改流程',
    description: 'OneAPI.fun 前端修改标准作业流程：从需求分析到代码变更到验证的完整 SOP。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "oneapi_sys_flow", "api"],
      capabilities: ["oneapi-sys-flow"],
      required_config: {},
    },
  },
  {
    id: 'wb-oneapi-work-rules',
    name: 'OneAPI 操作规范',
    description: 'OneAPI.fun 项目强制操作规范：涉及 OneAPI 项目的任何操作必须遵守此规则。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "oneapi_work_rules", "api"],
      capabilities: ["oneapi-work-rules"],
      required_config: {},
    },
  },
  {
    id: 'wb-claude-code-agnes-context-fix',
    name: '上下文溢出修复',
    description: '修复 Claude Code ContextWindowExceeded 错误，自动压缩和截断过长的上下文窗口。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "claude_code_agnes_co"],
      capabilities: ["claude-code-agnes-context-fix"],
      required_config: {},
    },
  },
  {
    id: 'wb-proactive-agent',
    name: '主动式 Agent',
    description: '将 AI Agent 从任务跟随者转化为主动行动者：自动发现机会、预判需求、主动执行。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "proactive_agent"],
      capabilities: ["proactive-agent"],
      required_config: {},
    },
  },
  {
    id: 'wb-xiucheng-self-improving-agent',
    name: '修成自我改进',
    description: '持续自我改进的 Agent 模式：反思日志、行动清单和迭代优化循环。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "xiucheng_self_improv"],
      capabilities: ["xiucheng-self-improving-agent"],
      required_config: {},
    },
  },
  {
    id: 'wb-oracle',
    name: '双模型审查 Oracle',
    description: '用 Oracle CLI 捆绑 prompt+文件提交给第二模型审查：调试、重构、设计检查、交叉验证。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "oracle"],
      capabilities: ["oracle"],
      required_config: {},
    },
  },
  {
    id: 'wb-skill-creator',
    name: '技能创建指南',
    description: '创建高效 Agent 技能的完整指南：结构、最佳实践、测试策略和发布流程。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "skill_creator"],
      capabilities: ["skill-creator"],
      required_config: {},
    },
  },
  {
    id: 'wb-skill-vetter',
    name: '技能安全审查',
    description: 'AI Agent 技能安全审查工具：检测权限滥用、数据泄露、命令注入等安全风险。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "skill_vetter"],
      capabilities: ["skill-vetter"],
      required_config: {},
    },
  },
  {
    id: 'wb-capability-evolver',
    name: '能力进化器',
    description: '自动发现 GitHub issue 并驱动 Agent 能力演进，持续提升 Agent 覆盖范围和质量。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "capability_evolver"],
      capabilities: ["capability-evolver"],
      required_config: {},
    },
  },
  {
    id: 'wb-autoresearch',
    name: '自主实验循环',
    description: 'AI Agent 自主实验循环：自动设计实验、执行验证、迭代优化，加速研究探索。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "autoresearch"],
      capabilities: ["autoresearch"],
      required_config: {},
    },
  },
  {
    id: 'wb-self-improving',
    name: '自我改进 Agent',
    description: '自我反思 + 自我批评 + 自我改进的三层循环，持续优化 Agent 行为和输出质量。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "self_improving"],
      capabilities: ["self-improving"],
      required_config: {},
    },
  },
  {
    id: 'wb-evolver',
    name: '进化器 (Evolver)',
    description: 'Agent 自进化引擎：自动识别能力缺口、生成改进方案、验证迭代效果。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "evolver"],
      capabilities: ["evolver"],
      required_config: {},
    },
  },
  {
    id: 'wb-no-repeat-loop',
    name: '防复读机 SOP',
    description: '防止 Agent 陷入复读机退化循环的 SOP，检测重复输出并触发策略切换。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "no_repeat_loop"],
      capabilities: ["no-repeat-loop"],
      required_config: {},
    },
  },
  {
    id: 'wb-feishu-evolver-wrapper',
    name: '飞书进化桥',
    description: '飞书集成的能力进化器包装层，将 Evolver 的自进化能力接入飞书工作流。',
    category: 'development',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'development',
      tags: ["development", "feishu_evolver_wrapp", "飞书"],
      capabilities: ["feishu-evolver-wrapper"],
      required_config: {},
    },
  },

  // ---- integration (系统集成) ----
  {
    id: 'wb-api-gateway',
    name: 'API 网关',
    description: '通过统一网关连接外部服务 API，支持多协议适配、认证管理和请求路由。',
    category: 'integration',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'integration',
      tags: ["integration", "api_gateway", "api"],
      capabilities: ["api-gateway"],
      required_config: {},
    },
  },
  {
    id: 'wb-mcporter',
    name: 'MCP 服务管理',
    description: '通过 mcporter CLI 列出、配置、认证和调用 MCP 服务器/工具，支持 HTTP 和 stdio 模式。',
    category: 'integration',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'integration',
      tags: ["integration", "mcporter", "mcp"],
      capabilities: ["mcporter"],
      required_config: {},
    },
  },
  {
    id: 'wb-tmux',
    name: 'tmux 远程控制',
    description: '远程控制 tmux 会话：发送按键、抓取输出、管理窗口和面板，适配交互式 CLI。',
    category: 'integration',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'integration',
      tags: ["integration", "tmux"],
      capabilities: ["tmux"],
      required_config: {},
    },
  },

  // ---- marketing (营销推广) ----
  {
    id: 'wb-seo',
    name: 'SEO 全套工具',
    description: 'SEO 专员 Agent：站点审计、内容优化、竞品分析、关键词研究和排名监控。',
    category: 'marketing',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'marketing',
      tags: ["marketing", "seo"],
      capabilities: ["seo"],
      required_config: {},
    },
  },
  {
    id: 'wb-seo-competitor-analysis',
    name: 'SEO 竞品分析',
    description: '深度 SEO 竞品分析：关键词差距、内容策略、外链对比和排名趋势追踪。',
    category: 'marketing',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'marketing',
      tags: ["marketing", "seo_competitor_analy"],
      capabilities: ["seo-competitor-analysis"],
      required_config: {},
    },
  },

  // ---- office (办公协作) ----
  {
    id: 'wb-apple-reminders',
    name: 'Apple 提醒事项',
    description: '通过 remin CLI 管理 Apple Reminders，创建待办、设置截止日期、完成任务。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "apple_reminders"],
      capabilities: ["apple-reminders"],
      required_config: {},
    },
  },
  {
    id: 'wb-apple-notes',
    name: 'Apple 笔记',
    description: '通过 memo CLI 管理 Apple Notes，创建、编辑、搜索和导出备忘录。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "apple_notes"],
      capabilities: ["apple-notes"],
      required_config: {},
    },
  },
  {
    id: 'wb-gog',
    name: 'Google Workspace',
    description: 'Google Workspace CLI：管理 Gmail、日历、Drive、通讯录、Sheets 和 Docs。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "gog"],
      capabilities: ["gog"],
      required_config: {},
    },
  },
  {
    id: 'wb-google-workspace-mcp',
    name: 'Google Workspace MCP',
    description: '通过 MCP 协议接入 Google Workspace：Gmail、Calendar、Drive、Docs、Sheets 全套服务。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "google_workspace_mcp", "mcp"],
      capabilities: ["google-workspace-mcp"],
      required_config: {},
    },
  },
  {
    id: 'wb-himalaya',
    name: 'IMAP 邮件 CLI',
    description: '通过 himalaya CLI 管理 IMAP/SMTP 邮件：收发、搜索、分类、转发，支持多账户。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "himalaya"],
      capabilities: ["himalaya"],
      required_config: {},
    },
  },
  {
    id: 'wb-imap-smtp-email',
    name: 'IMAP/SMTP 邮件',
    description: '通过 IMAP/SMTP 协议收发邮件，支持多账户配置、HTML 邮件和附件处理。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "imap_smtp_email", "邮件"],
      capabilities: ["imap-smtp-email"],
      required_config: {},
    },
  },
  {
    id: 'wb-tiangong-notebooklm-cli',
    name: 'NotebookLM',
    description: 'NotebookLM CLI 包装：导入来源、生成摘要、创建音频概述和知识问答。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "tiangong_notebooklm_"],
      capabilities: ["tiangong-notebooklm-cli"],
      required_config: {},
    },
  },
  {
    id: 'wb-obsidian',
    name: 'Obsidian 笔记',
    description: '操作 Obsidian 知识库：创建/编辑 Markdown 笔记、搜索标签、管理双向链接。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "obsidian"],
      capabilities: ["obsidian"],
      required_config: {},
    },
  },
  {
    id: 'wb-nano-pdf',
    name: 'PDF 编辑器',
    description: '用自然语言指令编辑 PDF：修改文本、调整布局、合并拆分、添加注释。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "nano_pdf"],
      capabilities: ["nano-pdf"],
      required_config: {},
    },
  },
  {
    id: 'wb-things-mac',
    name: 'Things 3 任务',
    description: '通过 Things CLI 管理 Things 3 任务：创建待办、设置标签、管理项目和区域。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "things_mac"],
      capabilities: ["things-mac"],
      required_config: {},
    },
  },
  {
    id: 'wb-trello',
    name: 'Trello 项目管理',
    description: '通过 Trello REST API 管理看板、列表和卡片：创建任务、移动卡片、追踪进度。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "trello"],
      capabilities: ["trello"],
      required_config: {},
    },
  },
  {
    id: 'wb-memory-manager',
    name: '本地记忆管理',
    description: 'Agent 本地记忆管理：创建、检索、更新和清除记忆条目，支持语义搜索和分类。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "memory_manager"],
      capabilities: ["memory-manager"],
      required_config: {},
    },
  },
  {
    id: 'wb-tencentcloud-cos',
    name: '腾讯云 COS',
    description: '腾讯云对象存储(COS)和数据万象(CI)：上传下载、图片处理、内容审核。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "tencentcloud_cos", "腾讯"],
      capabilities: ["tencentcloud-cos"],
      required_config: {},
    },
  },
  {
    id: 'wb-cos-vectors',
    name: '腾讯云 COS 向量库',
    description: '管理腾讯云 COS 向量桶：上传文档、检索向量、管理索引，支持 RAG 和语义搜索。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "cos_vectors"],
      capabilities: ["cos-vectors"],
      required_config: {},
    },
  },
  {
    id: 'wb-tencent-meeting-skill',
    name: '腾讯会议',
    description: '腾讯会议视频会议管理：预约会议、查看记录、获取纪要和参会人管理。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "tencent_meeting_skil", "腾讯"],
      capabilities: ["tencent-meeting-skill"],
      required_config: {},
    },
  },
  {
    id: 'wb-tencent-docs',
    name: '腾讯文档',
    description: '腾讯文档在线云文档平台：创建、编辑、管理文档、表格和演示文稿。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "tencent_docs", "腾讯"],
      capabilities: ["tencent-docs"],
      required_config: {},
    },
  },
  {
    id: 'wb-金山文档-wps云文档',
    name: '金山文档| WPS云文档',
    description: 'description_zh: 金山文档官方 Skill，对话即操作——知识存入、接龙转表格、文档转MD、收发表生成',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "金山文档| wps云文档"],
      capabilities: ["金山文档|_wps云文档"],
      required_config: {},
    },
  },
  {
    id: 'wb-feishu-doc-manager',
    name: '飞书文档管理',
    description: '飞书云文档管理器：创建、编辑、搜索和组织飞书文档，支持多种文档类型。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "feishu_doc_manager", "飞书"],
      capabilities: ["feishu-doc-manager"],
      required_config: {},
    },
  },
  {
    id: 'wb-feishu-messaging',
    name: '飞书消息',
    description: '飞书即时通讯：收发消息、搜索群聊、查找群成员、管理群组，支持富文本和卡片消息。',
    category: 'office',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'office',
      tags: ["office", "feishu_messaging", "飞书"],
      capabilities: ["feishu-messaging"],
      required_config: {},
    },
  },

  // ---- social (社媒运营) ----
  {
    id: 'wb-bilibili-hot-monitor',
    name: 'B站热门监控',
    description: '生成 B 站热门视频日报并发送邮件，覆盖视频热度排行、分区趋势和创作者动态。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "bilibili_hot_monitor"],
      capabilities: ["bilibili-hot-monitor"],
      required_config: {},
    },
  },
  {
    id: 'wb-gifgrep',
    name: 'GIF 搜索下载',
    description: '搜索 GIF 图库、下载动图、提取静态帧和预览图，支持多源搜索和批量操作。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "gifgrep"],
      capabilities: ["gifgrep"],
      required_config: {},
    },
  },
  {
    id: 'wb-spotify-player',
    name: 'Spotify 播放器',
    description: '终端 Spotify 播放/搜索：控制播放、搜索歌曲、管理播放列表和收藏。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "spotify_player"],
      capabilities: ["spotify-player"],
      required_config: {},
    },
  },
  {
    id: 'wb-telegram-api',
    name: 'Telegram Bot API',
    description: 'Telegram Bot API 集成：发送消息、管理聊天、处理更新和用户交互，支持认证管理。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "telegram_api", "api"],
      capabilities: ["telegram-api"],
      required_config: {},
    },
  },
  {
    id: 'wb-telegram',
    name: 'Telegram 工作流设计',
    description: '设计 Telegram Bot 工作流和命令驱动对话：直接 HTTPS 请求，无需 SDK。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "telegram"],
      capabilities: ["telegram"],
      required_config: {},
    },
  },
  {
    id: 'wb-wacli',
    name: 'WhatsApp 消息',
    description: '通过 wacli CLI 发送 WhatsApp 消息、搜索和同步聊天历史记录。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "wacli"],
      capabilities: ["wacli"],
      required_config: {},
    },
  },
  {
    id: 'wb-xurl',
    name: 'X/Twitter 情报',
    description: 'Twitter 研究和内容情报：分析 Profile、Thread、对话，识别痛点提取内容角度。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "xurl"],
      capabilities: ["xurl"],
      required_config: {},
    },
  },
  {
    id: 'wb-x-twitter',
    name: 'X/Twitter 研究',
    description: 'X/Twitter 内容研究和情报分析：分析推文、提取观点、追踪话题趋势。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "x_twitter"],
      capabilities: ["x-twitter"],
      required_config: {},
    },
  },
  {
    id: 'wb-youtube-api-skill',
    name: 'YouTube API',
    description: 'YouTube Data API 集成：搜索视频、管理播放列表、访问频道数据和评论互动。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "youtube_api_skill", "api"],
      capabilities: ["youtube-api-skill"],
      required_config: {},
    },
  },
  {
    id: 'wb-imsg',
    name: 'iMessage 管理',
    description: 'iMessage/SMS CLI：列出对话、查看历史、发送消息、实时监听新消息。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "imsg"],
      capabilities: ["imsg"],
      required_config: {},
    },
  },
  {
    id: 'wb-x-ai',
    name: 'xAI Grok 模型',
    description: '通过 xAI API 与 Grok 模型对话：支持 Grok-3、Grok-3-mini、视觉和多轮对话。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "x_ai"],
      capabilities: ["x-ai"],
      required_config: {},
    },
  },
  {
    id: 'wb-xiaohongshu',
    name: '小红书运营',
    description: '小红书内容运营：笔记发布、数据分析、热门趋势追踪和关键词优化。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "xiaohongshu"],
      capabilities: ["xiaohongshu"],
      required_config: {},
    },
  },
  {
    id: 'wb-wechat-mp-publisher1',
    name: '微信公众号发布',
    description: '远程微信公众号发布技能：通过 HTTP MCP 解决发布难题，合规优化版。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "wechat_mp_publisher1", "微信"],
      capabilities: ["wechat-mp-publisher1"],
      required_config: {},
    },
  },
  {
    id: 'wb-wechat-publisher',
    name: '微信内容发布',
    description: '微信内容发布与管理：草稿创建、定时发布、素材管理和数据统计。',
    category: 'social',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'social',
      tags: ["social", "wechat_publisher", "微信"],
      capabilities: ["wechat-publisher"],
      required_config: {},
    },
  },

  // ---- strategy (商业策略) ----
  {
    id: 'wb-musk-first-principles-perspective',
    name: '第一性原理思维',
    description: '蒸馏 Elon Musk 的第一性原理思维框架，辅助商业决策和创业战略分析。',
    category: 'strategy',
    version: '1.0.0',
    author: 'workbuddy',
    installs: 100,
    rating: 4.0,
    manifest: {
      version: '1.0.0',
      author: 'workbuddy',
      category: 'strategy',
      tags: ["strategy", "musk_first_principle"],
      capabilities: ["musk-first-principles-perspective"],
      required_config: {},
    },
  },
];

export function getMarketplaceEntry(id: string): MarketplaceEntry | undefined {
  return MARKETPLACE_CATALOG.find((s) => s.id === id);
}

export function searchMarketplace(query: string, category?: string): MarketplaceEntry[] {
  let results = MARKETPLACE_CATALOG;
  if (category && category !== 'all') {
    results = results.filter((s) => s.category === category);
  }
  if (query) {
    const q = query.toLowerCase();
    results = results.filter(
      (s) =>
        s.name.toLowerCase().includes(q) ||
        s.description.toLowerCase().includes(q) ||
        s.manifest.tags.some((t) => t.toLowerCase().includes(q)),
    );
  }
  return results;
}

export const MARKETPLACE_CATEGORIES = [
  { value: 'all', label: '全部' },
  { value: 'office', label: '办公协作' },
  { value: 'development', label: '开发工具' },
  { value: 'social', label: '社媒运营' },
  { value: 'design', label: '视觉设计' },
  { value: 'data', label: '数据分析' },
  { value: 'automation', label: '自动化' },
  { value: 'content', label: '内容创作' },
  { value: 'marketing', label: '营销推广' },
  { value: 'integration', label: '系统集成' },
  { value: 'strategy', label: '商业策略' },
  { value: 'custom', label: '通用工具' },
] as const;
